[package]
name = "lavan-proc-macros"
version = "0.0.1"
authors = ["Sabi <sabitheotome@tutanota.de>"]
description = "Lavan utility proc-macros"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
proc-macro2 = "1.0.83"
syn = { version = "2.0.66", features = ["full"] }

